#!/usr/bin/env python3
# NOTE: after regenerating, run: xcrun swift format --in-place --configuration .swift-format --recursive Sources

"""Generate Sources/SwaTex/Layout/KaTeXSvgData.swift from RaTeX's katex_svg.rs.

Extracts every `const NAME: &str = "..."` and `const NAME: [&str; N] = [...]`
declaration (KaTeX raw SVG path data) and emits Swift `static let` constants,
faithfully applying Rust string-literal semantics:

  - `\\` at end of line: skip the newline and all leading whitespace of the
    next line (Rust line continuation).
  - Embedded raw newlines are preserved (emitted as `\n` escapes in Swift).
  - `\\\\`, `\\"`, `\\n`, `\\t` escapes are decoded then re-encoded for Swift.

Usage:
  python3 scripts/gen_katex_svg_data.py <path/to/katex_svg.rs> <output.swift>
"""

import re
import sys


def parse_rust_string(src: str, i: int) -> tuple[str, int]:
    """Parse a Rust string literal starting at src[i] == '"'. Returns (value, next_index)."""
    assert src[i] == '"', f"expected '\"' at {i}"
    i += 1
    out = []
    while i < len(src):
        c = src[i]
        if c == '"':
            return "".join(out), i + 1
        if c == "\\":
            nxt = src[i + 1]
            if nxt == "\n":
                # Line continuation: skip newline and leading whitespace.
                i += 2
                while i < len(src) and src[i] in " \t":
                    i += 1
                continue
            elif nxt == "n":
                out.append("\n")
            elif nxt == "t":
                out.append("\t")
            elif nxt == "\\":
                out.append("\\")
            elif nxt == '"':
                out.append('"')
            else:
                raise ValueError(f"unhandled escape \\{nxt} at {i}")
            i += 2
        else:
            out.append(c)
            i += 1
    raise ValueError("unterminated string literal")


def swift_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def swift_name(rust_name: str) -> str:
    parts = rust_name.lower().split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def preceding_comments(src: str, decl_start: int) -> list[str]:
    """Collect contiguous `//` comment lines immediately above the declaration."""
    lines = src[:decl_start].split("\n")
    # Last element is the indent of the declaration line itself; drop it.
    lines = lines[:-1]
    comments = []
    for line in reversed(lines):
        stripped = line.strip()
        if stripped.startswith("//"):
            comments.append(stripped)
        else:
            break
    return list(reversed(comments))


def main() -> None:
    rs_path, out_path = sys.argv[1], sys.argv[2]
    src = open(rs_path, encoding="utf-8").read()

    decls = []  # (name, comments, value_or_list)
    # Match both scalar and array const declarations of &str.
    pattern = re.compile(
        r"^(?:pub(?:\(crate\))?\s+)?const\s+([A-Z0-9_]+)\s*:\s*(&str|\[&str;\s*(\d+)\])\s*=",
        re.MULTILINE,
    )
    for m in pattern.finditer(src):
        name = m.group(1)
        if name.startswith("_"):
            # Unused/dead data in the Rust source (e.g. `_VEC_KATEX`); skip.
            continue
        comments = preceding_comments(src, m.start())
        i = m.end()
        if m.group(2) == "&str":
            while src[i] != '"':
                i += 1
            value, i = parse_rust_string(src, i)
            decls.append((name, comments, value))
        else:
            count = int(m.group(3))
            values = []
            while src[i] != "[":
                i += 1
            i += 1
            for _ in range(count):
                # Skip whitespace, commas, and `// comment` lines between entries.
                while src[i] != '"':
                    if src[i] == "/" and src[i + 1] == "/":
                        while src[i] != "\n":
                            i += 1
                    i += 1
                value, i = parse_rust_string(src, i)
                values.append(value)
            decls.append((name, comments, values))

    lines = [
        "// Generated by scripts/gen_katex_svg_data.py from RaTeX katex_svg.rs.",
        "// Do not edit by hand — rerun the script to regenerate.",
        "//",
        "// KaTeX raw SVG path data (from KaTeX `svgGeometry.js`).",
        "",
        "enum KaTeXSvgData {",
    ]
    for name, comments, value in decls:
        for c in comments:
            lines.append(f"    {c}")
        if isinstance(value, list):
            lines.append(f"    static let {swift_name(name)}: [String] = [")
            for v in value:
                lines.append(f'        "{swift_escape(v)}",')
            lines.append("    ]")
        else:
            lines.append(f'    static let {swift_name(name)} = "{swift_escape(value)}"')
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    total = sum(len(v) if isinstance(v, list) else 1 for _, _, v in decls)
    print(f"wrote {out_path}: {len(decls)} declarations, {total} path strings")


if __name__ == "__main__":
    main()
